version: '3.8'

services:
  backend_app:
    build:
      context: .
      dockerfile: ./docker/backend.dockerfile
    ports:
      - '5000:5000'
    volumes:
      - ./:/app
#    command: "uvicorn app.app:app --host='0.0.0.0' --port=8000 --debug"