version: '3'

services:
  backend_app:
    build:
      context: .
      dockerfile: ./docker/backend.dockerfile
    ports:
      - '5000:5000'
    volumes:
      - ./:/app

    depends_on:
      - db

  db:
    restart: always
    build:
      context: .
      dockerfile: ./docker/db.dockerfile
    ports:
      - '6432:5432'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db